@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Fri Feb 28 11:12:24 +0100 2025
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto a24645a9595f427180664ecc12f904cb --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot Tb_task1_single_delay_behav xil_defaultlib.Tb_task1_single_delay -log elaborate.log"
call xelab  -wto a24645a9595f427180664ecc12f904cb --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot Tb_task1_single_delay_behav xil_defaultlib.Tb_task1_single_delay -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
